version: "3.3"
services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    ports:
      - 8008:8008
    volumes:
      - ./synapse-data:/data
    environment:
      - SYNAPSE_SERVER_NAME=192.168.1.33
      - SYNAPSE_REPORT_STATS=no

  mautrix-whatsapp:
    image: dock.mau.dev/mautrix/whatsapp:latest
    container_name: mautrix-whatsapp
    restart: unless-stopped
    volumes:
      - ./whatsapp-data:/data
    depends_on:
      - synapse
